<?php
namespace console\controllers;

use common\models\Post;
use yii\console\Controller;

class HelloController extends Controller{
    public $rev;
//    public function actionIndex(){//index 是默认动作
//        echo "Hello World! \n";
//    }
    public function options($actionID)
    {
        return array_merge(parent::options($actionID),['rev']) ; // TODO: Change the autogenerated stub
    }

    public function optionAliases()
    {
        return array_merge(parent::optionAliases(),['r'=>'rev']) ; // TODO: Change the autogenerated stub
    }

    public function actionIndex(){
        if ($this->rev==1){
            echo strrev("Hello World!")."\n";
        }
        else{
            echo "Hello World!\n";
        }
    }
    public function actionList(){
        header('Content-type: text/html;charset=utf-8');
        $post=Post::find()->all();
        foreach ($post as $apost){
           echo iconv('utf-8','gbk//IGNORE',($apost['id']." - ".$apost['title']."\n"));
        }
    }

    public function actionWho($name){
        echo ("hello ". $name."!\n");
    }

    public function actionAll(array $names){
        var_dump($names);
    }
}